# Generated by Django 5.0.4 on 2024-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='image2',
            field=models.ImageField(null=True, upload_to='colors/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image3',
            field=models.ImageField(null=True, upload_to='colors/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image4',
            field=models.ImageField(null=True, upload_to='colors/'),
        ),
    ]
